<?php
echo '<!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="utf-8" />
            <meta name="description" content="Goto Gro MRM" />
            <meta name="keywords" content="HTML5, CSS layout" />
            <meta name="author" content="Group Tuesday"  />
            <title>Goto Gro MRM</title>
            <link href="style/style.css" rel="stylesheet">
        </head>'
?>

