<?php
echo '<header>
        <h1>Goto Gro MRM</h1>
        <nav id="menu">
            <a href="index.php">Home</a> 
            <a href="add-member.php">Add Member</a>
            <a href="add-grocery.php">Add Grocery Item</a>
            <a href="add-sales-record.php">Add Sales Record</a>
            <a href="edit-sales-record.php">Edit Sales Record</a>
            <a href="edit-grocery-record.php">Edit Grocery Item</a>
            <a href="edit-member-record.php">Edit Member Record</a>
            <a href="request-report.php">Report</a>
        </nav>
    </header>';
?>